### ISSUE TITLE
Problem with entities_prefLabels.ttl

### ISSUE THREAD

**Issue by abedegno** [ldbc/ldbc_spb_bm_2.0#5]
entities_prefLabels.ttl appears to contain many unescaped backslashes cause parse errors.

**Comment by venkot** [comment]
Can you specify which RDF framework are you using for parsing? Currently tested with Sesame RDF framework and Virtuoso which don't complain about those unescaped backslashes.

**Comment by venkot** [comment]
Fixed in last commit
